// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Alur struct {
	ID         uuid.UUID        `json:"id"`
	OperasiID  pgtype.UUID      `json:"operasi_id"`
	SkenarioID pgtype.UUID      `json:"skenario_id"`
	Alur       pgtype.Text      `json:"alur"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Building struct {
	ID         uuid.UUID        `json:"id"`
	OperasiID  pgtype.UUID      `json:"operasi_id"`
	SkenarioID pgtype.UUID      `json:"skenario_id"`
	Name       pgtype.Text      `json:"name"`
	Keterangan pgtype.Text      `json:"keterangan"`
	Color      pgtype.Text      `json:"color"`
	Geom       pgtype.Text      `json:"geom"`
	Height     pgtype.Int4      `json:"height"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Category struct {
	ID        uuid.UUID        `json:"id"`
	Name      pgtype.Text      `json:"name"`
	Icon      pgtype.Text      `json:"icon"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Command struct {
	ID         uuid.UUID        `json:"id"`
	OperasiID  pgtype.UUID      `json:"operasi_id"`
	SkenarioID pgtype.UUID      `json:"skenario_id"`
	MarkerID   pgtype.UUID      `json:"marker_id"`
	Command    pgtype.Text      `json:"command"`
	Data       pgtype.Text      `json:"data"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type LastMap struct {
	ID         uuid.UUID        `json:"id"`
	OperasiID  pgtype.UUID      `json:"operasi_id"`
	SkenarioID pgtype.UUID      `json:"skenario_id"`
	CenterX    pgtype.Float8    `json:"center_x"`
	CenterY    pgtype.Float8    `json:"center_y"`
	Zoom       pgtype.Float8    `json:"zoom"`
	Bearing    pgtype.Float8    `json:"bearing"`
	Pitch      pgtype.Float8    `json:"pitch"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type LastPosition struct {
	ID         uuid.UUID        `json:"id"`
	OperasiID  pgtype.UUID      `json:"operasi_id"`
	SkenarioID pgtype.UUID      `json:"skenario_id"`
	MarkerID   pgtype.UUID      `json:"marker_id"`
	RotX       pgtype.Float8    `json:"rot_x"`
	RotY       pgtype.Float8    `json:"rot_y"`
	RotZ       pgtype.Float8    `json:"rot_z"`
	PosX       pgtype.Float8    `json:"pos_x"`
	PosY       pgtype.Float8    `json:"pos_y"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Marker struct {
	ID         uuid.UUID        `json:"id"`
	OperasiID  pgtype.UUID      `json:"operasi_id"`
	SkenarioID pgtype.UUID      `json:"skenario_id"`
	UnitID     pgtype.UUID      `json:"unit_id"`
	Name       pgtype.Text      `json:"name"`
	Kategori   pgtype.Text      `json:"kategori"`
	Jumlah     pgtype.Int4      `json:"jumlah"`
	RotX       pgtype.Float8    `json:"rot_x"`
	RotY       pgtype.Float8    `json:"rot_y"`
	RotZ       pgtype.Float8    `json:"rot_z"`
	PosX       pgtype.Float8    `json:"pos_x"`
	PosY       pgtype.Float8    `json:"pos_y"`
	Keterangan pgtype.Text      `json:"keterangan"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	Scale      pgtype.Float8    `json:"scale"`
}

type Operasi struct {
	ID        uuid.UUID        `json:"id"`
	Name      pgtype.Text      `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Skenario struct {
	ID        uuid.UUID        `json:"id"`
	OperasiID pgtype.UUID      `json:"operasi_id"`
	Name      pgtype.Text      `json:"name"`
	CenterX   pgtype.Float8    `json:"center_x"`
	CenterY   pgtype.Float8    `json:"center_y"`
	Zoom      pgtype.Float8    `json:"zoom"`
	MaxZoom   pgtype.Float8    `json:"max_zoom"`
	Pitch     pgtype.Float8    `json:"pitch"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID         uuid.UUID        `json:"id"`
	Name       pgtype.Text      `json:"name"`
	Username   pgtype.Text      `json:"username"`
	Password   pgtype.Text      `json:"password"`
	Role       pgtype.Text      `json:"role"`
	UnitID     pgtype.UUID      `json:"unit_id"`
	ProfileImg pgtype.Text      `json:"profile_img"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	Units      pgtype.Text      `json:"units"`
}
