// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCategories(ctx context.Context) (int64, error)
	CountOperasis(ctx context.Context) (int64, error)
	CountSearchCategories(ctx context.Context, name string) (int64, error)
	CountSearchOperasis(ctx context.Context, name string) (int64, error)
	CreateBuilding(ctx context.Context, arg CreateBuildingParams) (Building, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCommand(ctx context.Context, arg CreateCommandParams) (Command, error)
	CreateLastMap(ctx context.Context, arg CreateLastMapParams) (LastMap, error)
	CreateLastPosition(ctx context.Context, arg CreateLastPositionParams) (LastPosition, error)
	CreateMarker(ctx context.Context, arg CreateMarkerParams) (Marker, error)
	CreateOperasi(ctx context.Context, name pgtype.Text) (Operasi, error)
	CreateSkenario(ctx context.Context, arg CreateSkenarioParams) (Skenario, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBuilding(ctx context.Context, id uuid.UUID) error
	DeleteCategories(ctx context.Context, id uuid.UUID) error
	DeleteMarkers(ctx context.Context, id uuid.UUID) error
	DeleteOperasis(ctx context.Context, id uuid.UUID) error
	DeleteSkenarios(ctx context.Context, id uuid.UUID) error
	GetCategories(ctx context.Context, id uuid.UUID) (Category, error)
	GetMarker(ctx context.Context, id uuid.UUID) (GetMarkerRow, error)
	GetOperasis(ctx context.Context, id uuid.UUID) (Operasi, error)
	GetSkenarios(ctx context.Context, id uuid.UUID) (GetSkenariosRow, error)
	ListBuildingsBySkenario(ctx context.Context, skenarioID pgtype.UUID) ([]ListBuildingsBySkenarioRow, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCommandsBySkenario(ctx context.Context, skenarioID pgtype.UUID) ([]Command, error)
	ListLastMapsBySkenario(ctx context.Context, skenarioID pgtype.UUID) ([]ListLastMapsBySkenarioRow, error)
	ListLastPositonsByMarkerId(ctx context.Context, markerID pgtype.UUID) ([]LastPosition, error)
	ListLastPositonsBySkenario(ctx context.Context, skenarioID pgtype.UUID) ([]LastPosition, error)
	ListMarkersBySkenario(ctx context.Context, skenarioID pgtype.UUID) ([]ListMarkersBySkenarioRow, error)
	ListOperasis(ctx context.Context) ([]Operasi, error)
	ListSkenariosByOperasi(ctx context.Context, operasiID pgtype.UUID) ([]ListSkenariosByOperasiRow, error)
	PaginateCategories(ctx context.Context, arg PaginateCategoriesParams) ([]Category, error)
	PaginateOperasis(ctx context.Context, arg PaginateOperasisParams) ([]Operasi, error)
	PaginateSearchCategories(ctx context.Context, arg PaginateSearchCategoriesParams) ([]Category, error)
	PaginateSearchOperasis(ctx context.Context, arg PaginateSearchOperasisParams) ([]Operasi, error)
	SelectUsers(ctx context.Context, username pgtype.Text) (SelectUsersRow, error)
	UpdateBuilding(ctx context.Context, arg UpdateBuildingParams) (Building, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateLastMaps(ctx context.Context, arg UpdateLastMapsParams) (LastMap, error)
	UpdateLastPositionMove(ctx context.Context, arg UpdateLastPositionMoveParams) (LastPosition, error)
	UpdateLastPositionRot(ctx context.Context, arg UpdateLastPositionRotParams) (LastPosition, error)
	UpdateMarkerGeom(ctx context.Context, arg UpdateMarkerGeomParams) (Marker, error)
	UpdateMarkerName(ctx context.Context, arg UpdateMarkerNameParams) (Marker, error)
	UpdateMarkerRotasi(ctx context.Context, arg UpdateMarkerRotasiParams) (Marker, error)
	UpdateMarkerScale(ctx context.Context, arg UpdateMarkerScaleParams) (Marker, error)
	UpdateOperasi(ctx context.Context, arg UpdateOperasiParams) (Operasi, error)
	UpdateSkenario(ctx context.Context, arg UpdateSkenarioParams) (Skenario, error)
}

var _ Querier = (*Queries)(nil)
